import React from 'react';
import ParticleAnimation from '@/components/particleAnimation/ParticleAnimation';
import Nav from '@/components/Nav/Nav';
import Footer from '@/components/Footer/Footer';
import Form from '@/components/Form/form';
import Head from 'next/head';

function News () {

  return (
    <>
      <Head>
        <title>Reklamax - Створити проект</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/png" sizes="32x32" href="/public/img/Logo.png" />
      </Head>
      <ParticleAnimation/>
      <div className='main'>
        <div className='container'>
          <Nav/>
          <Form/>
          <Footer/>
        </div>
      </div>
    </>
  )
}

export default News 